### ISSUE TITLE
Cannot locate adress bar or display list of opened tabs in Nightly 72

### ISSUE THREAD

**Issue by lukaszgo1** [javidominguez/MozillaScripts#6] opened 2019-11-25 13:25 UTC
1. Open Nightly 72.0a1 (2019-11-24) (64-bit)
2. Press NVDA+a or NVDA+F8.

In both these cases NVDA announces not available here.

I am running aforementioned version of Nightly on Windows 7 with NVDA 2019.2.1 and Mozilla Apps Enhancements Version: 1.9.1

**Comment by lukaszgo1** [comment] 2019-11-25 17:24
Quick investigation revealed that in Nightly 72  main window no longer has IA2Attribute id  main-window therefore method inMainWindow fails.

**Comment by lukaszgo1** [comment] 2020-01-10 13:56
Firefox 72 has been released a few days ago, and this problem is present there, making some functionalities of this add-on no longer working.

**Comment by javidominguez** [comment] 2020-01-11 18:02
Hi. Thanks for the report. Excuse me I have not responded before. The issue is fixed in the latest [release 1.9.2](https://github.com/javidominguez/MozillaScripts/tree/1.9.2)

**Closed by javidominguez** 2020-01-11 18:02 UTC
